### ISSUE TITLE
I want to define the order of groups/documents in my navigation

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#150]
Currently I'm using workarounds like this on from Susy…

```yaml
groups:
  a-config: 'Configuration'
  b-api: 'Grid Functions'
  plugin-utils: 'Plugin Utilities'
  plugin_svg-grid: 'Plugin: SVG Grid Image'
  su-math: 'Su: Core Math Engine'
  x-normal: '[Susy Normalization]'
  x-parser: '[Susy Syntax Parser]'
  x-validation: '[Su Input Validation]'
```
