### ISSUE TITLE
I want a second layer of "grouping" in the navigation.

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#228]
The sidebar can get quite long, quickly – and often there are logical page-groups such as "configuration", "design tokens", "patterns", 'components", "layouts", etc. I propose handling this in the Herman config, where we already allow group-sorting & naming.

**Comment by jgerigmeyer** [comment]
Currently, we just use the standard SassDoc `groups` option (http://sassdoc.com/configuration/#groups); there is no Herman-specific config here.

How do you propose subgroups would be defined in the config?

**Comment by mirisuzanne** [comment]
I was imagining nested lists:

```yaml
groups:
  - Configuration:
    - config-colors: _Colors
    - config-fonts: _Fonts
  - Patterns:
    - pattern-buttons: _Buttons
    - pattern-inputs: _Inputs
```
