### ISSUE TITLE
Support for common non-CSS font-weight names?

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#250]
e.g. 'thin', 'light', 'demibold', etc. These would have to be associated with numbers for CSS output.

See: https://www.w3.org/TR/css-fonts-3/#font-weight-prop

**Comment by robsonsobral** [comment]
The one I use on my framework:

``` scss
/// Convert font weights names to numbers. Names can be any case,
/// dash or separated separated or not separated at all.
///
/// @access public
/// @group helpers
/// @param {String} $weight - Weight name
/// @return {Number}
/// @link https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight?v=control#Common_weight_name_mapping
///
/// @example scss
/// h1 {
/// 	font-weight: font-weight('medium');
/// }
@function font-weight($weight: 'normal') {

	$default-weights: (
		'thin': 100,
		'hairline': 100,
		'extralight': 200,
		'extra light': 200,
		'extra-light': 200,
		'ultralight': 200,
		'ultra light': 200,
		'ultra-light': 200,
		'light': 300,
		'normal': 400,
		'medium': 500,
		'semibold': 600,
		'semi bold': 600,
		'semi-bold': 600,
		'demibold': 600,
		'demi bold': 600,
		'demi-bold': 600,
		'bold': 700,
		'extrabold': 800,
		'extra bold': 800,
		'extra-bold': 800,
		'ultrabold': 800,
		'ultra bold': 800,
		'ultra-bold': 800,
		'black': 900,
		'heavy': 900
	);

	$weight: to-lower-case($weight);

	@if variable-exists('font-weights') and type-of($font-weights) =='map' {
		$default-weights: map-merge($default-weights, $font-weights);
	}

	@if not map-has-key($default-weights, $weight) {
		@error 'unknown value sent to `font-weight` function-> #{$weight}.';
	}

	@return map-get($default-weights, $weight);
}

```

Maybe it helps.
