### ISSUE TITLE
Allow nav-subsection titles to have their own contents

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#305]
It's often useful to provide global docs for an entire section of the navigation. I don't know the best yml representation, but it would be replacing something like this:

```yml
groups:
  'Plugin: Animate':
    animate: 'Getting Started'
    animate-times: 'Timing'
    animate-ease: 'Easing'
  'Plugin: Color':
    color: 'Getting Started'
    color-api: 'Colors'
    color-contrast: 'Contrast'
```
