### ISSUE TITLE
A way to easily use hierarchical accoutrement maps in Herman

### ISSUE THREAD

**Issue by johncrim** [oddbird/sassdoc-theme-herman#345]
Given an accoutrement map like the following:

```scss
@use 'accoutrement' as a;

$colors: (
  'white': #f8f8f8,
  'warm-offwhite': hsl(28, 25, 93),
  'contrast-dark': #444,
  'contrast-light': #f8f8f8cc,
  'page': (
    'background': '#white'
  ),
  'header': (
    'background': '#white',
  ),
  'footer': (
    'background': hsl(240,67%,94%) ('shade': 80%),
  )
);
@include a.add-colors($colors); 
```

If I add these colors to the herman map, using:

```scss
@use 'herman';

/// @group colors
/// @colors site-colors
@include herman.herman-add('colors', 'site-colors', $colors);
```

The values in the root of the map are displayed correctly, but the submaps, and references, aren't. This problem isn't specific to displaying colors in herman - it would also be great to resolve and display accoutrement sizes, fonts, etc in herman.

If there were an accoutrement function that "flattened" the above map to:
```scss
$colors: (
  'white': #f8f8f8,
  'warm-offwhite': hsl(28, 25, 93),
  'contrast-dark': #444,
  'contrast-light': #f8f8f8cc,
  'page->background': #f8f8f8,
  'header->background': #f8f8f8,
  'footer->background': hsl(240,67%,94%) ('shade': 80%)
);
```

And then the color swatch rendering combined all keys with the same value under a single swatch (it may already do this), life would be great.

**Comment by johncrim** [comment]
It turns out, this function was easier to write than I thought it would be. Here's what I came up with:

```scss
@use 'accoutrement' as a;

/// Resolves all the values in $map starting with $root.
/// Needed to turn accoutrement maps into something that Herman can display
@function flatten-accoutrement-map($map, $root: '') {
  $enumMap: null;
  @if ($root == '') {
    $enumMap: $map;
  }
  @else {
    $enumMap: a.get-token($map, $root)
  }

  @if (type-of($enumMap) != 'map') {
    $result: (
      $root: $enumMap
    );
    @return $result;
  }
  @else {
    $result: ();
    @each $key, $value in $enumMap {
      $flattened-key: '#{$root}->#{$key}';
      @if ($root == '') {
        $flattened-key: $key;
      }
      @if (type-of($value) == 'map') {
        $result: map.merge($result, flatten-accoutrement-map($map, $flattened-key));
      }
      @else {
        $addMap: ($flattened-key: $value);
        $result: map.merge($result, $addMap)
      }
    }
    @return $result;
  }
}
```

And it can be used like this to display the contents of hierarchical accoutrement maps in Herman:

```scss
@use 'herman';

/// @group colors
/// @colors site-colors
@include herman.herman-add('colors', 'site-colors', flatten-accoutrement-map(site-colors.$colors));

/// Site sizes for screens below desktop
/// @group site-sizes
/// @sizes site-sm-sizes {ruler}
@include herman.herman-add('sizes', 'site-sm-sizes', flatten-accoutrement-map(a.$sizes, 'sm'));

/// Site sizes for desktop+
/// @group site-sizes
/// @sizes site-lg-sizes {ruler}
@include herman.herman-add('sizes', 'site-lg-sizes', flatten-accoutrement-map(a.$sizes, 'lg'));
```

Herman does already display multiple map keys with the same value together (yay!).

I'll leave this here in case it's useful to others. It would be awesome IMO if this were added to accoutrement or herman.
