### ISSUE TITLE
JSON not being exported

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/sassdoc-theme-herman#358]
I'm sorry! I tried a lot, but I keep getting:

```
» [WARNING] Error reading file: ./build/sass-docs__exported.json
ENOENT: no such file or directory, open 'E:\_repositories\initial-css\build\sass-docs__exported.json'
```

The `abstracts/_index.scss` has:

```
@use '../../node_modules/sassdoc-theme-herman/scss/utilities';

/// Test
/// @colors brand-colors
/// @group colors
$colors: (
  'brand-colors': (
    'brand-orange': '#c75000',
    'brand-blue': '#0d7fa5',
  ),
  'status-colors': (
    'go': '#657e1b',
    'yield': '#c75000',
  ),
);

$herman: (
  'colors': $colors,
);

// Export to JSON
// @use '../../node_modules/sassdoc-theme-herman/scss/utilities' with (
//   $herman: $herman,
// );

// Export to JSON
@include utilities.export($herman);
```

The `.sassdocrc` file:

```
autofill:
  - "throw"
  - "content"
  - "require"
dest:
  - "./build"
exclude:
  - "./css/*"
  - "stylesheets/vendor/*"
groups:
  undefined: "General"
  components: "CSS components"
  configurations: "Configurations"
  font-stacks: "Font-stacks"
  qa: "Quality assurance"
  hacks: "Dirty Hacks & Fixes"
  helpers: "Helpers"
  normalizer: "Normalization"

  # testing
  # all items will be listed in the order given...
  api-config: Configuration
  api-json: Exporting Styles to JSON
  # testing
  # nested objects will create named subgroups...
  Public API:
    api-colors: Color Palettes
    api-fonts: Font Specimens
    api-scale: Ratios & Sizes
  Design Tokens:
    config-colors: _Colors
    config-fonts: _Fonts



package: "./package.json"
strict: true
theme: "herman"
verbose: true

display:
  access:
    - private
    - public
  alias: true
  watermark: true
  descriptionPath: "README.md"

herman:
  extraLinks:
  displayColors:
    - "hsl"
    - "hex"
  sass:
    jsonFile: "./build/sass-docs__exported.json"
    includePaths:
      - "./stylesheets/abstracts"
    use:
      - file: "constants"
        namespace: "*"
      - file: "font-stacks"
        namespace: "*"
      - file: "mixins"
        namespace: "*"
```

Can somebody help me, please?
